version: "3.8"

services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run db:generate && npm run db:migrate && npm run dev"
    restart: unless-stopped
