version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-file:./dev.db}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - PORT=${PORT:-8000}
    command: sh -c "npm install && npm run db:generate && npm run db:migrate && npm run dev"
    restart: unless-stopped
